Fix 'Classpath element does not exist' error in test generation
If the target project does not contain any tests, the test generation
task failed with the following:

[main] ERROR EvoSuite - Fatal crash on main EvoSuite process.
java.lang.IllegalArgumentException: Classpath element does not exist
on disk at: /{path}/commons-lang--number-utils/target/test-classes ...

This commit fixes this by excluding the test-classes path from the
classpath during test generation.